### ISSUE TITLE
what is the gif from?

### ISSUE THREAD

**Issue by meandavejustice** [ungoldman/valis.pw#1]
I was just talking to a friend about pkd and remembered you telling me about valis and this site. Now I'm wondering where is this gif from?

**Comment by ungoldman** [comment]
Hi @meandavejustice! It appears that I may have lost track of this issue. To answer your question, this image comes from the 1988 video game Snatcher, which was re-released on Sega CD in 1995. The game was written and designed by Hideo Kojima, creator of the Metal Gear series.

https://youtu.be/oNxMWfpSI6A?t=115

I hope you are well!

**Comment by ungoldman** [comment]
I skipped ahead a bit to get to the part with the skull but it's pretty great right away.

https://www.youtube.com/watch?v=oNxMWfpSI6A&t=34s

<img width="548" alt="Screen Shot 2022-03-11 at 5 51 08 PM" src="https://user-images.githubusercontent.com/427322/157999119-490693dd-febc-4f68-ad40-6420888d75ec.png">

**Comment by meandavejustice** [comment]
Awesome, thanks for sharing!
